services:
  api:
    build:
      context: ./MiniEcommerce.Api
      dockerfile: Dockerfile
    container_name: miniecommerce-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres-db;Port=5432;Database=EcommerceDb;Username=admin;Password=Password123!
      - ConnectionStrings__Redis=redis-cache:6379
    depends_on:
      - postgres-db
      - redis-cache

  postgres-db:
    image: postgres:15-alpine
    container_name: miniecommerce-postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Password123!
      POSTGRES_DB: EcommerceDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis-cache:
    image: redis:7-alpine
    container_name: miniecommerce-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: